### ISSUE TITLE
Automatically close issues

### ISSUE THREAD

**Issue by fpg1503** [ajdlinux/KernelPRBot#2]
Shouldn't KernelPRBot automatically close the issues after sending the message?

**Comment by daxtens** [comment]
That's an interesting idea. Unfortunately, we can't, as we're not admins of
torvalds/linux.

**Comment by ajdlinux** [comment]
As @daxtens says, we'd need admin access on the repo to do that, and for some reason I don't think that'll happen. :)

I may at some stage implement support for this in the underlying bot script (ajdlinux/PRBot) in case any other projects who are able to grant admin access to the bot want to use it. (Though if you've got admin access you should probably use a webhooks-based bot rather than a scraper)
